repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: mixed-line-ending
    -   id: sort-simple-yaml

- repo: https://github.com/ansible/ansible-lint
  rev: v4.1.1a3
  hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$
default_stages: [prepare-commit-msg, commit, push]
