---
- name: All
  hosts: all
  connection: local
  gather_facts: yes
  vars_files:
    - files/vars.yml
  tasks:
    - name: Setup | Scripts folder
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: 0755

    - import_tasks: tasks/apt.yml
      become: yes
      tags: apt

    - import_tasks: tasks/terminal.yml
      tags: terminal

    - import_tasks: tasks/java.yml
      tags:
        - language
        - java

    - import_tasks: tasks/code.yml
      tags:
        - application
        - vscode

    - import_tasks: tasks/node.yml
      tags:
        - language
        - node
