- name: All Tasks
  hosts: all
  connection: local
  gather_facts: true
  vars_files:
    - files/vars.yml
  tasks:
    - name: Setup | Scripts folder
      become: true
      ansible.builtin.file:
        path: '{{ install_dir }}'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        state: directory
        mode: 0755

    - ansible.builtin.import_tasks: tasks/packages.yml
      tags: packages

    - ansible.builtin.import_tasks: tasks/terminal.yml
      tags: terminal

    - ansible.builtin.import_tasks: tasks/golang.yml
      tags:
        - language
        - golang

    - ansible.builtin.import_tasks: tasks/java.yml
      tags:
        - language
        - java

    - ansible.builtin.import_tasks: tasks/ruby.yml
      tags:
        - language
        - ruby

    - ansible.builtin.import_tasks: tasks/node.yml
      tags: node

    - ansible.builtin.import_tasks: tasks/python.yml
      tags: python

    - ansible.builtin.import_tasks: tasks/git.yml
      tags: git

    - ansible.builtin.import_tasks: tasks/hashicorp.yml
      tags: hashicorp

    - ansible.builtin.import_tasks: tasks/cloud.yml
      tags: cloud

    - ansible.builtin.import_tasks: tasks/docker.yml
      tags: docker

    - ansible.builtin.import_tasks: tasks/applications/vscode.yml
      tags:
        - applications
        - vscode

    - ansible.builtin.import_tasks: tasks/applications/jetbrains.yml
      tags:
        - applications
        - jetbrains

    - ansible.builtin.import_tasks: tasks/ssh.yml
      tags: ssh

    - ansible.builtin.import_tasks: tasks/popos.yml
      tags: popos

    - ansible.builtin.import_tasks: tasks/applications/vmware.yml
      when: "'vmware' in group_names"
      tags:
        - applications
        - vmware

    - ansible.builtin.import_tasks: tasks/brew.yml
      tags: brew

    - ansible.builtin.import_role:
        name: artis3n.tailscale
      vars:
        tailscale_auth_key: '{{ TAILSCALE_AUTH_KEY }}'

  handlers:
    - ansible.builtin.import_tasks: handlers/handlers.yml
