- name: All Tasks
  hosts: all
  connection: local
  gather_facts: yes
  vars_files:
    - files/vars.yml
  roles:
    - name: artis3n.tailscale
      vars:
        tailscale_auth_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32313231643962663130656134646639303633316464636262326334323161323232376230653433
          3465633637663531333136663430646531393064623030630a383338396537383734343539363466
          62373533616466633535323530376438323562363263363063373834303963393065363334653937
          3363353464343333350a333965353431396163653437313731313364363439313432666236626430
          33316636346631636264333734323935646533323736303966333036376362653439
  collections:
    - artis3n.github
  tasks:
    - name: Setup | Scripts folder
      file:
        path: '{{ install_dir }}'
        state: directory
        mode: 0755

    - import_tasks: tasks/packages.yml
      tags: packages

    - import_tasks: tasks/terminal.yml
      tags: terminal

    - import_tasks: tasks/java.yml
      tags:
        - language
        - java

    - import_tasks: tasks/ruby.yml
      tags:
        - language
        - ruby

    - import_tasks: tasks/node.yml
      tags: node

    - import_tasks: tasks/git.yml
      tags: git

    - import_tasks: tasks/hashicorp.yml
      tags: hashicorp

    - import_tasks: tasks/docker.yml
      tags: docker

    - import_tasks: tasks/cloud.yml
      tags: cloud

    - import_tasks: tasks/applications/jetbrains.yml
      tags:
        - applications
        - jetbrains

    - import_tasks: tasks/ssh.yml
      tags: ssh

    - import_tasks: tasks/popos.yml
      tags: popos

    - import_tasks: tasks/applications/vmware.yml
      when: "'vmware' in group_names"
      tags:
        - applications
        - vmware

    - import_tasks: tasks/brew.yml
      tags: brew

  handlers:
    - import_tasks: handlers/handlers.yml
