- name: All Tasks
  hosts: all
  connection: local
  gather_facts: 'yes'
  vars_files:
    - files/vars.yml
  collections:
    - artis3n.github
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: '{{ ansible_user }}'
          visual_studio_code_extensions:
            - Shan.code-settings-sync
  tasks:
    - name: Setup | Scripts folder
      file:
        path: '{{ install_dir }}'
        state: directory
        mode: 0755

    - import_tasks: tasks/packages.yml
      tags: packages

    - import_tasks: tasks/terminal.yml
      tags: terminal

    - import_tasks: tasks/java.yml
      tags:
        - language
        - java

    - import_tasks: tasks/git.yml
      tags: git

    - import_tasks: tasks/terraform.yml
      tags: terraform

    - import_tasks: tasks/docker.yml
      tags: docker

    - import_tasks: tasks/applications/jetbrains.yml
      tags:
        - applications
        - jetbrains

    - import_tasks: tasks/ssh.yml
      tags: ssh

  handlers:
    - import_tasks: handlers/handlers.yml
