- name: Pre Tasks
  hosts: all
  connection: local
  gather_facts: true
  vars_files:
    - files/vars.yml
  tasks:
    - name: Install Apt packages
      become: true
      ansible.builtin.apt:
        name: '{{ apt_pre_dependencies }}'
        update_cache: true
        state: present
      notify: Restart

    - ansible.builtin.import_role:
        name: artis3n.docker

  handlers:
    - name: Restart
      ansible.builtin.debug:
        msg: Pre-packages have been installed. Restart the machine, then run `make provision`.
