---

- name: Alfa driver | Install dependencies
  become: yes
  apt:
    name: "{{ alfa_driver_dependencies }}"
    state: present

- name: Alfa driver | Clone repository
  git:
    repo: https://github.com/gnab/rtl8812au.git
    dest: "{{ install_dir }}/rtl8812au/"
    # Latest commit from 2-year old repo
    version: 2807a0a2b71cc47c7483f2a9638c66438c83c5da
  register: alfa_dir

- name: Alfa driver | Make
  command: make && touch {{ install_dir }}/alfa-maked
  args:
    chdir: "{{ alfa_dir.dest }}"
    creates: "{{ install_dir }}/alfa-maked"

- name: Alfa driver | Get kernel release
  shell: |
    set -o pipefail
    uname -r | sed 's/-generic//'
  changed_when: false
  register: kernel_version

- name: Alfa driver | Add to kernel
  become: yes
  command: insmod 8812au.ko && cp 8812au.ko /lib/modules/{{ kernel_version.stdout }}/kernel/drivers/net/wireless && depmod
  args:
    chdir: "{{ alfa_dir.dest }}"
    creates: /lib/modules/{{ kernel_version.stdout }}/kernel/drivers/net/wireless/8812au.ko

- name: Alfa driver | Create source file directory
  become: yes
  file:
    path: /usr/src/8812au-{{ kernel_version.stdout }}
    state: directory
    owner: root
    group: root

- name: Alfa driver | Set source files
  become: yes
  copy:
    src: "{{ install_dir }}/rtl8812au/*"
    dest: /usr/src/8812au-{{ kernel_version.stdout }}
    owner: root
    group: root

- name: Alfa driver | Build kernel module
  become: yes
  command: |
    dkms add -m 8812au -v {{ kernel_version.stdout }} && dkms build -m 8812au -v {{ kernel_version.stdout }} && \
    dkms install -m 8812au -v {{ kernel_version.stdout }} && touch {{ install_dir }}/alfa-installed
  args:
    chdir: "{{ alfa_dir.dest }}"
    creates: "{{ install_dir }}/alfa-installed"

- name: Alfa driver | Add to modules list
  become: yes
  lineinfile:
    path: /etc/modules
    line: 8812au
    state: present
    backup: yes
