---

- name: Alfa driver | Install dependencies
  become: yes
  apt:
    name: "{{ alfa_driver_dependencies }}"
    state: present

- name: Alfa driver | Clone repository
  git:
    repo: https://github.com/gnab/rtl8812au.git
    dest: "{{ install_dir }}/rtl8812au/"
    # Latest commit from 2-year old repo
    version: 2807a0a2b71cc47c7483f2a9638c66438c83c5da
  register: alfa_dir

- name: Alfa driver | Make
  shell: make && touch {{ install_dir }}/alfa-maked
  args:
    chdir: "{{ install_dir }}/rtl8812au"
    creates: "{{ install_dir }}/alfa-maked"

- name: Alfa driver | Get kernel release
  command: uname -r
  changed_when: false
  register: kernel_release

- name: Alfa driver | Check if kernel is loaded
  command: modinfo 8812au
  register: alfa_driver_loaded
  failed_when: alfa_driver_loaded.rc > 1
  changed_when: false

- name: Alfa driver | Load into kernel
  become: yes
  command: insmod 8812au.ko
  args:
    chdir: "{{ install_dir }}/rtl8812au"
  when: alfa_driver_loaded.rc != 0

- name: Alfa driver | Generate kernel files
  become: yes
  shell: cp 8812au.ko /lib/modules/{{ kernel_release.stdout }}/kernel/drivers/net/wireless && depmod
  args:
    chdir: "{{ install_dir }}/rtl8812au"
    creates: /lib/modules/{{ kernel_release.stdout }}/kernel/drivers/net/wireless/8812au.ko

- name: Alfa driver | Create source file directory
  become: yes
  file:
    path: /usr/src/8812au-4.2.2
    state: directory
    owner: root
    group: root

- name: Alfa driver | Set source files
  become: yes
  shell: cp -r {{ install_dir }}/rtl8812au/* /usr/src/8812au-4.2.2/ && chown -R root:root /usr/src/8812au-4.2.2/
  args:
    creates: /usr/src/8812au-4.2.2/8812au.ko


- name: Alfra driver | Check if module is built
  become: yes
  shell: |
    set -o pipefail
    dkms status -m 8812au | grep "installed"
  args:
    executable: /bin/bash
  register: alfa_driver_built
  changed_when: false
  failed_when: alfa_driver_built.rc > 1

- name: Alfa driver | Build kernel module
  become: yes
  shell: |
    dkms add -m 8812au -v 4.2.2 && dkms build -m 8812au -v 4.2.2 && dkms install -m 8812au -v 4.2.2 && \
    touch {{ install_dir }}/alfa-installed
  args:
    chdir: "{{ install_dir }}/rtl8812au/"
    creates: "{{ install_dir }}/alfa-installed"
  when: alfa_driver_built.rc != 0

- name: Alfa driver | Add to modules list
  become: yes
  lineinfile:
    path: /etc/modules
    line: 8812au
    state: present
    backup: yes
