---

- name: Applications | Bitwarden | Download
  get_url:
    url: https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=appimage
    dest: "{{ ansible_env.HOME }}/Documents/{{ bitwarden_appimage }}"
    mode: 0764
  notify: Bitwarden added

- name: Application | Jetbrains Toolbox | Download
  get_url:
    url: https://data.services.jetbrains.com/products/download?platform=linux&code=TBA
    dest: "{{ install_dir }}/{{ jetbrains_toolbox }}"
    mode: 0644
  register: toolbox_app

- name: Application | Jetbrains Toolbox | Un-package
  unarchive:
    src: "{{ toolbox_app.dest }}"
    dest: "{{ install_dir }}/"
    remote_src: yes
  when: toolbox_app.changed # noqa 503

- name: Application | Jetbrains Toolbox | Locate installer
  shell: |
    set -o pipefail
    find . -maxdepth 1 -type d -name "jetbrains-toolbox-\*" -print | head -n1
  args:
    executable: /bin/bash
    chdir: "{{ install_dir }}"
  changed_when: false
  register: toolbox_installer

- name: Application | Jetbrains Toolbox | Install
  command: bash {{ toolbox_installer.stdout }}/jetbrains-toolbox
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/applications/jetbrains-toolbox.desktop"

- name: Application | VMWare | Download
  get_url:
    url: https://www.vmware.com/go/getworkstation-linux
    dest: "{{ install_dir }}/vmware.bundle"
    mode: 0764
  register: vmware_installer

- name: Application VMWare | Install
  command: bash {{ vmware_installer.dest }}
  args:
    creates: /usr/bin/vmware
