---

- name: Apt | Install dependencies
  apt:
    name: "{{ apt_dependencies }}"
    state: present

- name: Apt | Add Repositories
  apt_repository:
    repo: ppa:{{ item }}
    state: present
  with_items: "{{ apt_repos }}"

- name: Apt | Install packages
  apt:
    name: "{{ apt_packages }}"
    state: present
  async: 3600
  poll: 60

- name: Apt | Upgrade packages
  apt:
    upgrade: full
  async: 3600
  poll: 60

- name: Apt | Clean up
  apt:
    autoremove: yes
    autoclean: yes
