---

- name: Apt | Install dependencies
  apt:
    name: "{{ apt_dependencies }}"
    update_cache: yes
    state: present

- name: Apt | Add Repositories
  apt_repository:
    repo: ppa:{{ item }}
    state: present
  with_items: "{{ apt_repos }}"

- name: Apt | Upgrade packages - This will take a long time
  apt:
    upgrade: full
    update_cache: yes
  async: 3600
  poll: 60

- name: Apt | Install primary packages - This will take a long time
  apt:
    name: "{{ apt_primary_packages }}"
    state: present
  async: 3600
  poll: 60

- name: Apt | Install secondary packages - This will take a long time
  apt:
    name: "{{ apt_secondary_packages }}"
    state: present
  async: 3600
  poll: 60

- name: Apt | Clean up
  apt:
    autoremove: yes
    autoclean: yes
