---

- name: Apt | Add Repositories
  apt_repository:
    repo: ppa:{{ item }}
    state: present
  with_items: "{{ apt_repos }}"

- name: Apt | Install packages
  apt:
    name: "{{ apt_packages }}"
    state: present
  async: 1800
  poll: 60

- name: Apt | Upgrade packages
  apt:
    upgrade: full

- name: Apt | Clean up
  apt:
    autoremove: yes
