- name: Apt | Install dependencies
  apt:
    name: '{{ apt_dependencies }}'
    update_cache: 'yes'
    state: present
  notify: Clean up apt
- name: Apt | Add Repositories
  apt_repository:
    repo: 'ppa:{{ item }}'
    state: present
  with_items: '{{ apt_repos }}'
- name: Apt | Upgrade packages - This will take a long time
  apt:
    upgrade: full
    update_cache: 'yes'
  notify: Clean up apt
- name: Apt | Install packages - This will take a long time
  apt:
    name: '{{ apt_packages }}'
    state: present
  notify: Clean up apt
