---

- name: Brew | Install homebrew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew
  tags: molecule-notest

- name: Brew | Add to path
  ansible.builtin.lineinfile:
    path: '{{ home_dir }}/{{ item }}'
    regexp: ^eval \$\(\/home\/linuxbrew\/\.linuxbrew\/bin\/brew shellenv\)
    line: eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    state: present
  loop:
    - '.zshrc'
    - '.bashrc'

- name: Brew | Add taps
  ansible.builtin.command: '{{ brew_executable }} tap {{ item.tap }}'
  args:
    creates: '{{ item.creates }}'
  loop: '{{ brew_taps }}'
  tags: molecule-notest

- name: Brew | Install gcc
  community.general.homebrew:
    name: gcc
    state: present
    path: /home/linuxbrew/.linuxbrew/bin
  tags: molecule-notest

- name: Brew | Install packages
  community.general.homebrew:
    name: '{{ homebrew_packages }}'
    state: present
    update_homebrew: true
    path: /home/linuxbrew/.linuxbrew/bin
  tags: molecule-notest
