---

- name: Brew | Install homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew
  tags: molecule-notest

- name: Brew | Add to path
  lineinfile:
    path: '{{ home_dir }}/{{ item }}'
    regexp: ^eval \$\(\/home\/linuxbrew\/\.linuxbrew\/bin\/brew shellenv\)
    line: eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    state: present
  loop:
    - '.zshrc'
    - '.bashrc'

- name: Brew | Add taps
  homebrew_tap:
    name: '{{ item }}'
    state: present
  loop: '{{ homebrew_taps }}'

- name: Brew | Add URL taps
  homebrew_tap:
    name: '{{ item.name }}'
    url: '{{ item.url }}'
    state: present
  loop: '{{ homebrew_url_taps }}'

- name: Brew | Install packages
  homebrew:
    name: '{{ homebrew_packages }}'
    state: present
    path: /home/linuxbrew/.linuxbrew/bin
  tags: molecule-notest
