---

- name: Cloud | Download AWS CLI
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: '{{ install_dir }}/awscliv2.zip'
  register: awscli_archive

- name: Cloud | Unarchive AWS CLI
  ansible.builtin.unarchive:
    src: '{{ awscli_archive.dest }}'
    remote_src: true
    dest: '{{ install_dir }}'
  register: new_awscli

- name: Cloud | Install AWS CLI
  become: true
  ansible.builtin.command: sh ./aws/install
  args:
    chdir: '{{ install_dir }}'
    creates: /usr/local/bin/aws

- name: Cloud | Update AWS CLI
  become: true
  ansible.builtin.command: sh ./aws/install --update
  args:
    chdir: '{{ install_dir }}'
  when: new_awscli.changed  # noqa 503
