---

- name: Docker | Ensure pip dependencies
  ansible.builtin.pip:
    name: '{{ docker_pip_dependencies }}'
    state: present
    executable: /usr/bin/pip3

- name: Docker | Goss | Install
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -fsSL https://goss.rocks/install | sh
    executable: /bin/bash
    creates: /usr/local/bin/goss

- name: Docker | Download images
  community.general.docker_image:
    name: '{{ item.name }}'
    source: pull
    state: present
    tag: '{{ item.tag }}'
  loop: '{{ docker_pull_images }}'

- name: Docker | Prune images
  community.general.docker_prune:
    images: true
