---

- name: Git | Set config
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { name: user.email, value: "{{ email }}" }
    - { name: user.name, value: "{{ handle }}" }
    - { name: push.default, value: simple }
    - { name: alias.ci, value: commit }
    - { name: alias.s, value: status }
    - { name: alias.br, value: branch }
    - { name: alias.co, value: checkout }
    - { name: alias.get, value: "pull --prune" }
    - { name: alias.list, value: "config --get-regexp alias" }
    - { name: alias.save, value: "stash save" }

- name: Git | Hub | Get latest version
  shell: |
    set -o pipefail
    curl https://api.github.com/repos/github/hub/releases/latest | jq .tag_name | cut -c 3- | rev | cut -c 2- | rev
  args:
    executable: /bin/bash
  register: hub_version
  changed_when: false

- name: Git | Hub | Download
  get_url:
    url: https://github.com/github/hub/releases/download/v{{ hub_version.stdout }}/hub-linux-amd64-{{ hub_version.stdout }}.tgz
    dest: "{{ install_dir }}/hub-linux-amd64-{{ hub_version.stdout }}.tgz"

- name: Git | Hub | Unarchive
  unarchive:
    src: "{{ install_dir }}/hub-linux-amd64-{{ hub_version.stdout }}.tgz"
    dest: "{{ install_dir }}/"
    creates: "{{ install_dir }}/hub-linux-amd64-{{ hub_version.stdout }}/bin/hub"

- name: Git | Hub | Add to local bin
  copy:
    src: "{{ install_dir }}/hub-linux-amd64-{{ hub_version.stdout }}/bin/hub"
    dest: "{{ ansible_env.HOME }}/.local/bin/hub"
    mode: 0751
