---

- name: Git | Set config
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { name: user.email, value: "{{ email }}" }
    - { name: user.name, value: "{{ name }}" }
    - { name: push.default, value: simple }
    - { name: alias.ci, value: commit }
    - { name: alias.s, value: status }
    - { name: alias.br, value: branch }
    - { name: alias.co, value: checkout }
    - { name: alias.get, value: "pull --prune" }
    - { name: alias.list, value: "config --get-regexp alias" }
    - { name: alias.save, value: "stash save" }
    - { name: commit.gpgsign, value: true }
    - { name: user.signingkey, value: "{{ gpg_keyid.stdout }}" }
