- name: Go | Ensure GOPATH
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  loop:
    - '{{ gopath }}'
    - '{{ gopath }}/src'
    - '{{ gopath }}/pkg'
    - '{{ gopath }}/bin'
