---

# - name: GPG | Generate key

- name: GPG | Add to git config
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { name: commit.gpgsign, value: true }
    - { name: user.signingkey, value: "{{ gpg_keyid.stdout }}" }
