---

- name: Secrets | Check for secrets file
  stat:
    path: "{{ lookup('env', 'PWD') }}/files/secrets.yml"
  register: secrets_file

- name: Secrets | Import secrets
  include_vars:
    file: "{{ lookup('env', 'PWD') }}/files/secrets.yml"
  when: secrets_file.stat.exists