---

- name: Java | Get Jabba install script
  get_url:
    url: https://github.com/shyiko/jabba/raw/master/install.sh
    dest: "{{ install_dir }}/{{ jabba_install_script }}"
    mode: 0764
  register: jabba_script

- name: Java | Install Jabba
  command: bash {{ jabba_script.dest }}
  args:
    creates: "{{ lookup('env', 'HOME') }}/.jabba/bin/jabba"

- name: Java | Add to profile
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: "[ -s '/home/{{ lookup('env', 'USER') }}/.jabba/jabba.sh' ] && source '/home/{{ lookup('env', 'USER') }}/.jabba/jabba.sh'"
    state: present

- name: Java | Install JDK
  command: "{{ lookup('env', 'HOME') }}/.jabba/bin/jabba install openjdk@{{ java_version }}"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.jabba/jdk/openjdk@{{ java_version }}"
