- name: Java | Get SDKMan install script
  get_url:
    url: 'https://get.sdkman.io'
    dest: '{{ install_dir }}/{{ sdkman_install_script }}'
    mode: 0755
  register: sdkman_script

- name: Java | Install SDKMan
  command: 'bash {{ sdkman_script.dest }}'
  args:
    creates: '/home/{{ ansible_user }}/.sdkman/bin/sdkman-init.sh'

- name: Java | Add to profile
  lineinfile:
    path: '/home/{{ ansible_user }}/.zshrc'
    line: "{{ item }}"
    state: present
  loop:
    - 'export SDKMAN_DIR="/home/{{ ansible_user }}/.sdkman"'
    - '[[ -s "/home/{{ ansible_user }}/.sdkman/bin/sdkman-init.sh" ]] && source "/home/{{ ansible_user }}/.sdkman/bin/sdkman-init.sh"'

- name: Java | Install JDK
  shell: "source /home/{{ ansible_user }}/.zshrc; sdk install java {{ sdkman_java_version | quote }}"
  args:
    executable: /bin/zsh
    creates: /home/{{ ansible_user }}/.sdkman/candidates/java/{{ sdkman_java_version }}/bin/java
