- name: Java | Get SDKMan install script
  get_url:
    url: 'https://get.sdkman.io'
    dest: '{{ install_dir }}/{{ sdkman_install_script }}'
    mode: 755
  register: sdkman_script

- name: Java | Install SDKMan
  command: 'bash {{ sdkman_script.dest }}'
  args:
    creates: '{{ lookup(''env'', ''HOME'') }}/.sdkman/bin/sdkman-init.sh'

- name: Java | Add to profile
  lineinfile:
    path: '{{ lookup(''env'', ''HOME'') }}/.zshrc'
    line: "{{ item }}"
    state: present
  loop:
    - 'export SDKMAN_DIR="{{ lookup(''env'', ''HOME'') }}/.sdkman"'
    - '[[ -s "{{ lookup(''env'', ''HOME'') }}/.sdkman/bin/sdkman-init.sh" ]] && source "{{ lookup(''env'', ''HOME'') }}/.sdkman/bin/sdkman-init.sh"'

- name: Java | Install JDK
  command: sdk install java {{ sdkman_java_version }}
  args:
    creates: '{{ lookup(''env'', ''HOME'') }}/.sdkman/candidates/java/{{ sdkman_java_version }}/bin/java'
