---

- name: Node | Download nvm
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh
    dest: "{{ install_dir }}/{{ nvm_install_script }}"
    mode: 0764

- name: Node | Install nvm
  command: bash "{{ install_dir }}/{{ nvm_install_script }}"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.nvm/nvm.sh"

- name: Node | Source nvm
  lineinfile:
    path: "{{ item }}"
    line: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    state: present
    create: yes
  with_items:
    - "{{ lookup('env', 'HOME') }}/bashrc"
    - "{{ lookup('env', 'HOME') }}/zshrc"

- name: Node | Install Node
  shell: source "{{ lookup('env', 'HOME') }}/.bashrc" && nvm install {{ node_version }}
  args:
    creates: "{{ lookup('env', 'HOME') }}/.nvm/versions/node/v{{ node_version }}/bin/node"
