---

- name: Node | Add apt-keys
  become: true
  ansible.builtin.apt_key:
    url: '{{ item }}'
    state: present
  loop: '{{ node_apt_keys }}'

- name: Node | Add repositories
  become: true
  ansible.builtin.apt_repository:
    repo: '{{ item }}'
    state: present
  loop: '{{ node_apt_repos }}'

- name: Node | Install Node
  become: true
  ansible.builtin.apt:
    name: '{{ node_apt_packages }}'
    update_cache: true
    state: present

- name: Node | Ensure global library directories
  become: true
  ansible.builtin.file:
    path: '{{ item.name }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '{{ item.mode }}'
    state: directory
  loop:
    - name: /usr/pnpm-global
      mode: '0755'

- name: Node | Ensure global library permissions
  become: true
  ansible.builtin.file:
    path: '{{ item.name }}'
    recurse: '{{ item.recurse }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  loop:
    - name: /usr/lib/node_modules
      recurse: true
    - name: /usr/bin
      recurse: false
    - name: /usr/pnpm-global
      recurse: false

- name: Node | Install global libraries
  community.general.npm:
    name: '{{ item }}'
    global: true
  loop: '{{ npm_global_packages }}'

- name: Deno | Install
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://deno.land/x/install/install.sh | sh
  args:
    executable: /bin/bash
    creates: '{{ deno_bin }}/deno'
