---

- name: Node | Get latest nvm release
  uri:
    url: https://api.github.com/repos/nvm-sh/nvm/releases/latest
    headers:
      Accept: application/vnd.github.v3+json
    body_format: json
    return_content: yes
  register: nvm_release

- name: Node | Set nvm version
  set_fact:
    nvm_version: "{{ nvm_release.json.tag_name[1:] }}"

- name: Node | Download nvm
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh
    dest: "{{ install_dir }}/{{ nvm_install_script }}"
    mode: 0764

- name: Node | Install nvm
  command: bash "{{ install_dir }}/{{ nvm_install_script }}"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.nvm/nvm.sh"

- name: Node | Add nvm to profiles
  lineinfile:
    path: "{{ item }}"
    line: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    state: present
    create: yes
  with_items:
    - "{{ lookup('env', 'HOME') }}/bashrc"
    - "{{ lookup('env', 'HOME') }}/zshrc"

- name: Node | Install Node
  shell: source {{ lookup('env', 'HOME') }}/.nvm/nvm.sh && nvm install {{ node_version }}
  args:
    creates: "{{ lookup('env', 'HOME') }}/.nvm/versions/node/v{{ node_version }}/bin/node"
    executable: /bin/bash
