- name: Packages | Apt | Install dependencies
  become: true
  ansible.builtin.apt:
    name: '{{ apt_dependencies }}'
    update_cache: true
    state: present
  notify: Clean up apt

- name: Packages | Apt | Add keys
  become: true
  ansible.builtin.apt_key:
    keyserver: '{{ item.server }}'
    id: '{{ item.keyid }}'
    state: present
  loop: '{{ apt_keys }}'

- name: Packages | Apt | Add keys (url)
  become: true
  ansible.builtin.apt_key:
    url: '{{ item }}'
    state: present
  loop: '{{ apt_keys_urls }}'

- name: Packages | Apt | Add repositories
  become: true
  ansible.builtin.apt_repository:
    repo: '{{ item }}'
    state: present
  loop: '{{ apt_repos }}'

- name: Packages | Apt | Upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
  notify: Clean up apt

- name: Packages | Apt | Install packages - Will take a long time
  become: true
  ansible.builtin.apt:
    name: '{{ apt_packages }}'
    state: present
  register: apt_install
  notify: Clean up apt

- name: Packages | Apt | Install deb from URL
  become: true
  ansible.builtin.apt:
    deb: '{{ item }}'
    state: present
  loop: '{{ apt_deb_urls }}'
  notify: Clean up apt

- name: Packages | Flatpak | Check for flathub
  ansible.builtin.shell: |
    set -o pipefail
    flatpak remotes | grep flathub
  args:
    executable: /bin/bash
  changed_when: false
  register: flathub_remote
  failed_when: flathub_remote.rc > 1

- name: Packages | Flatpak | Set up flathub
  ansible.builtin.command:
    cmd: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  when: flathub_remote.rc != 0

- name: Packages | Flatpak | Install applications
  community.general.flatpak:
    name: "{{ item }}"
    method: user
    state: present
  loop: "{{ flatpak_applications }}"

- name: Packages | Snap | Install core
  become: true
  ansible.builtin.shell:
    cmd: snap install core && touch {{ install_dir }}/.snap-core
    creates: '{{ install_dir }}/.snap-core'
  tags:
    - molecule-notest

- name: Packages | Snap | Install applications
  become: true
  community.general.snap:
    name: '{{ item.name }}'
    classic: '{{ item.classic }}'
    state: present
  loop: '{{ snap_apps }}'
  tags:
    - molecule-notest
