---

- name: Pentest | Install packages
  become: yes
  apt:
    name: "{{ pentest_packages }}"
    state: present
  async: 900
  poll: 15

- name: Pentest | John | Download
  git:
    repo: https://github.com/magnumripper/JohnTheRipper.git
    version: "{{ john_jumbo_branch }}"
    dest: "{{ install_dir }}/john"

- name: Pentest | John | Build
  shell: ./configure && make -s clean && make -sj4
  args:
    chdir: "{{ install_dir }}/john/src"
    creates: "{{ install_dir }}/john/run/john"
  async: 300
  poll: 10

- name: Pentest | John | Alias
  lineinfile:
    path: /home/{{ ansible_user }}/.zshrc
    regexp: "^alias john="
    line: 'alias john="{{ install_dir }}/john/run/john"'
    state: present
