---

- name: Pentest | Install packages
  become: yes
  apt:
    name: "{{ pentest_packages }}"
    state: present
  async: 900
  poll: 15

- name: Pentest | Download John - jumbo
  git:
    repo: https://github.com/magnumripper/JohnTheRipper.git
    version: "{{ john_jumbo_branch }}"
    dest: "{{ install_dir }}/john"

- name: Pentest | Build John - jumbo
  shell: ./configure && make -s clean && make -sj4
  args:
    chdir: "{{ install_dir }}/john/src"
    creates: "{{ install_dir }}/john/run/john"
  async: 300
  poll: 10
