---

- name: Ruby | Add repository
  become: yes
  apt_repository:
    repo: ppa:{{ rvm_repo }}
    state: present

- name: Ruby | Install RVM
  become: yes
  apt:
    name: rvm
    state: present
    update_cache: yes

- name: Ruby | Check for existing Ruby version
  stat:
    path: "{{ ansible_env.HOME }}/.rvm/rubies/ruby-{{ ruby_version }}"
  register: ruby_path

- name: Ruby | Install Ruby version
  command: "{{ ansible_env.HOME }}/.rvm/bin/rvm install ruby-{{ ruby_version }}"
  async: 1800
  poll: 30
  args:
    creates: "{{ ansible_env.HOME }}/.rvm/rubies/ruby-{{ ruby_version }}/bin/ruby"
