---

- name: Ruby | Set lib permissions
  become: yes
  file:
    path: '{{ item.name }}'
    recurse: yes
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    state: '{{ item.state }}'
    mode: 0644
  loop:
    - { name: '/var/lib/gems', state: 'directory' }
