---

- name: Ruby | Set lib permissions
  become: true
  ansible.builtin.file:
    path: '{{ item.name }}'
    recurse: true
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    state: '{{ item.state }}'
  loop:
    - name: '/var/lib/gems'
      state: 'directory'
