---

- name: Ruby | Add repository
  become: yes
  apt_repository:
    repo: ppa:{{ rvm_repo }}
    state: present

- name: Ruby | Install RVM
  become: yes
  apt:
    name: "{{ rvm_package }}"
    state: present
    update_cache: yes

- name: Ruby | Configure rvmrc
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.rvmrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ rvm_config_list }}"

- name: Ruby | Check for existing Ruby version
  stat:
    path: "{{ lookup('env', 'HOME') }}/.rvm/rubies/ruby-{{ ruby_version }}"
  register: ruby_path

- name: Ruby | Install Ruby version
  command: /usr/share/rvm/bin/rvmsudo /usr/share/rvm/bin/rvm install ruby-{{ ruby_version }}
  async: 1800
  poll: 30
  args:
    creates: "{{ lookup('env', 'HOME') }}/.rvm/rubies/ruby-{{ ruby_version }}/bin/ruby"
