---

- name: Ruby | Set lib permissions
  become: true
  ansible.builtin.file:
    path: /var/lib/gems/
    recurse: true
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    state: directory
