---

- name: SSH | Generate key
  openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/{{ ssh_keypair.filename }}"
    comment: "{{ ssh_keypair.comment }}"
    state: present
    type: "{{ ssh_keypair.type }}"
