---

- name: SSH | Ensure directory
  ansible.builtin.file:
    path: '{{ home_dir }}/.ssh'
    state: directory
    mode: 0700

- name: SSH | Generate key
  community.crypto.openssh_keypair:
    path: '{{ home_dir }}/.ssh/{{ ssh_keypair.filename }}'
    comment: '{{ ssh_keypair.comment }}'
    state: present
    type: '{{ ssh_keypair.type }}'
  register: gen_ssh_key

- name: SSH | Set default key
  ansible.builtin.template:
    src: ../files/ssh/config.j2
    dest: '{{ home_dir }}/.ssh/config'
    backup: true
    mode: 0600
