- name: SSH | Ensure directory
  file:
    path: '{{ home_dir }}/.ssh'
    state: directory

- name: SSH | Generate key
  openssh_keypair:
    path: '{{ home_dir }}/.ssh/{{ ssh_keypair.filename }}'
    comment: '{{ ssh_keypair.comment }}'
    state: present
    type: '{{ ssh_keypair.type }}'
  register: gen_ssh_key

- name: SSH | Set default key
  template:
    src: files/ssh/config.j2
    dest: '{{ home_dir }}/.ssh/config'
    backup: 'yes'
