- name: SSH | Ensure directory
  file:
    path: /home/{{ ansible_user }}/.ssh
    state: directory

- name: SSH | Generate key
  openssh_keypair:
    path: /home/{{ ansible_user }}/.ssh/{{ ssh_keypair.filename }}
    comment: '{{ ssh_keypair.comment }}'
    state: present
    type: '{{ ssh_keypair.type }}'
  register: gen_ssh_key

- name: SSH | Set default key
  template:
    src: files/ssh/config.j2
    dest: /home/{{ ansible_user }}/.ssh/config
    backup: 'yes'
