- name: Terminal | Install Oh My ZSH
  expect:
    command: bash -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    responses:
      'Do you want to change your default shell to zsh\? \[Y\/n]': 'Y'
  args:
    creates: /home/{{ ansible_user }}/.zshrc

- name: Terminal | Set Spaceship version
  set_fact:
    spaceship_version: >-
      {{ lookup('artis3n.github.latest_release', 'denysdovhan/spaceship-prompt')
      }}

- name: Terminal | ZSH Spaceship theme
  become: 'yes'
  git:
    repo: 'https://github.com/denysdovhan/spaceship-prompt.git'
    version: '{{ spaceship_version }}'
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/themes/spaceship-prompt
  register: spaceship_repo

- name: Terminal | Set file permissions
  become: 'yes'
  file:
    path: /home/{{ ansible_user }}/.oh-my-zsh/custom/themes/spaceship-prompt
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: 'yes'
  when: spaceship_repo.changed  # noqa 503

- name: Terminal | ZSH Spaceship symbolic link
  become: 'yes'
  file:
    src: /home/{{ ansible_user }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme
    state: link
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Terminal | Set Spaceship as the terminal theme
  become: 'yes'
  lineinfile:
    path: /home/{{ ansible_user }}/.zshrc
    regexp: ^ZSH_THEME=
    line: ZSH_THEME="spaceship"
    state: present

- name: Terminal | Add plugins
  lineinfile:
    path: /home/{{ ansible_user }}/.zshrc
    regexp: ^plugins=
    line: 'plugins=({{ zsh_plugins | join('' '') }})'
    state: present

- name: Terminal | Set default shell
  become: yes
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- name: Terminal | Set default editor
  alternatives:
    name: editor
    path: /usr/bin/vim
