---

- name: Terminal | Install Oh My ZSH
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.zshrc"

- name: Terminal | Get latest Spaceship release
  uri:
    url: https://api.github.com/repos/denysdovhan/spaceship-prompt/releases/latest
    headers:
      Accept: application/vnd.github.v3+json
    body_format: json
    return_content: yes
  register: spaceship_release

- name: Terminal | Set Spaceship version
  set_fact:
    spaceship_version: "{{ spaceship_release.json.tag_name }}"

- name: Terminal | ZSH Spaceship theme
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    version: "{{ spaceship_version }}"
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/spaceship-prompt"

- name: Terminal | ZSH Spaceship symbolic link
  file:
    src: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link

- name: Terminal | Set Spaceship as the terminal theme
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    regexp: "^ZSH_THEME="
    line: ZSH_THEME="spaceship"
    state: present

- name: Terminal | Add plugins
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    regexp: "^plugins="
    line: "plugins=({{ zsh_plugins | join(' ') }})"
    state: present
