---

- name: Wine | Enable i386 architecture
  become: yes
  lineinfile:
    dest: '/var/lib/dpkg/arch'
    line: 'i386'
    create: True
    state: present
  register: i386_arch

- name: Wine | Add public key
  become: yes
  apt_key:
    url: https://dl.winehq.org/wine-builds/winehq.key
    state: present

- name: Wine | Add repo
  become: yes
  apt_repository:
    repo: deb https://dl.winehq.org/wine-builds/ubuntu/ {{ ansible_distribution_release }} main
    state: present
  register: wine_repo

- name: Wine | Update cache
  become: yes
  apt:
    update_cache: yes
  when: i386_arch.changed or wine_repo.changed  # noqa 503

- name: Wine | Install packages
  become: yes
  apt:
    name: "{{ wine_packages }}"
    state: present
    install_recommends: True
