---

- name: Wine | Check if i386 is enabled
  become: yes
  shell: |
    set -o pipefail
    dpkg --print-foreign-architectures | grep i386
  args:
    executable: /bin/bash
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1

- name: Wine | Add DPKG architecture
  become: yes
  command: dpkg --add-architecture ie386
  when: result_i386_check.rc == 1

- name: Wine | Add public key
  become: yes
  apt_key:
    url: https://dl.winehq.org/wine-builds/winehq.key
    state: present

- name: Wine | Add repo
  become: yes
  apt_repository:
    repo: deb https://dl.winehq.org/wine-builds/ubuntu/ {{ ansible_distribution_release }} main
    state: present

- name: Wine | Install
  become: yes
  apt:
    name: "{{ wine_packages }}"
    update_cache: yes
    install_recommends: yes
    state: present
