---

- name: Check if i386 is enabled
  become: yes
  shell: |
    set -o pipefail
    dpkg --print-foreign-architectures | grep i386
  args:
    executable: /bin/bash
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1

- debug:
    var: result_i386_check

- name: Add DPKG architecture
  become: yes
  command: dpkg --add-architecture ie386
  when: result_i386_check.rc == 1

- name: Add Wine key
  become: yes
  apt_key:
    url: https://dl.winehq.org/wine-builds/winehq.key
    state: present

- name: Add Wine repo
  become: yes
  apt_repository:
    repo: deb https://dl.winehq.org/wine-builds/ubuntu/ {{ ansible_distribution_release }} main
    state: present

- name: Install Wine
  become: yes
  apt:
    name: winehq-stable
    update_cache: yes
    install_recommends: yes
    state: present
