---

- name: Wine | Add DPKG architecture
  become: yes
  command: dpkg --add-architecture ie386 && touch {{ install_dir }}/.wine_arch_touched
  args:
    creates: "{{ install_dir }}/.wine_arch_touched"

- name: Wine | Add public key
  become: yes
  apt_key:
    url: https://dl.winehq.org/wine-builds/winehq.key
    state: present

- name: Wine | Add repo
  become: yes
  apt_repository:
    repo: deb https://dl.winehq.org/wine-builds/ubuntu/ {{ ansible_distribution_release }} main
    state: present

- name: Wine | Install
  become: yes
  apt:
    name: winehq-stable
    update_cache: yes
    install_recommends: yes
    state: present
