---

- name: Clean up apt
  become: yes
  apt:
    autoremove: yes
    autoclean: yes

- name: Run keyboard lights
  become: yes
  systemd:
    name: kbd-color.service
    state: started
  tags: notest

- name: Restart Docker
  become: yes
  service:
    name: docker
    state: restarted

- name: Docker user added
  debug:
    msg: "A new user has been added to the Docker group. Please log out and log back in for this change to apply to the existing user."
