- name: Converge
  hosts: all
  gather_facts: 'yes'
  vars_files:
    - ../../files/vars.yml
  collections:
    - artis3n.github
  tasks:
    - name: Setup | Scripts folder
      file:
        path: '{{ install_dir }}'
        state: directory
        mode: 0755

    - import_tasks: ../../tasks/packages.yml
      become: 'yes'
      tags: apt

    - import_tasks: ../../tasks/terminal.yml
      tags: terminal

    - import_tasks: ../../tasks/java.yml
      tags:
        - language
        - java

    - import_tasks: ../../tasks/ruby.yml
      tags:
        - language
        - ruby

    - import_tasks: ../../tasks/node.yml
      tags: node

    - import_tasks: ../../tasks/git.yml
      tags: git

    - import_tasks: ../../tasks/hashicorp.yml
      tags: hashicorp

    - import_role:
        name: artis3n.docker
      tags: docker

    - import_tasks: ../../tasks/cloud.yml
      tags: cloud

    - import_tasks: ../../tasks/applications/jetbrains.yml
      tags:
        - applications
        - jetbrains

    - import_tasks: ../../tasks/ssh.yml
      tags: ssh

    - import_tasks: ../../tasks/popos.yml
      tags: popos

    - import_tasks: ../../tasks/applications/vmware.yml
      when: "'vmware' in group_names"
      tags:
        - applications
        - vmware

    - import_tasks: ../../tasks/brew.yml
      tags: brew

  handlers:
    - import_tasks: ../../handlers/handlers.yml
