- name: Converge
  hosts: all
  gather_facts: true
  vars_files:
    - ../../files/vars.yml
  tasks:
    - name: Setup | Scripts folder
      ansible.builtin.file:
        path: '{{ install_dir }}'
        state: directory
        mode: 0755

    - name: Packages
      ansible.builtin.import_tasks: ../../tasks/packages.yml
      become: true
      tags: apt

    - name: Terminal
      ansible.builtin.import_tasks: ../../tasks/terminal.yml
      tags: terminal

    - name: Go
      ansible.builtin.import_tasks: ../../tasks/golang.yml
      tags:
        - language
        - golang

    - name: Java
      ansible.builtin.import_tasks: ../../tasks/java.yml
      tags:
        - language
        - java

    - name: Ruby
      ansible.builtin.import_tasks: ../../tasks/ruby.yml
      tags:
        - language
        - ruby

    - name: Node
      ansible.builtin.import_tasks: ../../tasks/node.yml
      tags: node

    - name: Python
      ansible.builtin.import_tasks: ../../tasks/python.yml
      tags: python

    - name: Git
      ansible.builtin.import_tasks: ../../tasks/git.yml
      tags: git

    - name: Hashicorp
      ansible.builtin.import_tasks: ../../tasks/hashicorp.yml
      tags: hashicorp

    - name: Import Docker
      ansible.builtin.import_role:
        name: artis3n.docker
      tags: docker

    - name: Cloud
      ansible.builtin.import_tasks: ../../tasks/cloud.yml
      tags: cloud

    - name: Docker
      ansible.builtin.import_tasks: ../../tasks/docker.yml
      tags: docker

    - name: VSCode
      ansible.builtin.import_tasks: ../../tasks/applications/vscode.yml
      tags:
        - applications
        - vscode

    - name: Jetbrains
      ansible.builtin.import_tasks: ../../tasks/applications/jetbrains.yml
      tags:
        - applications
        - jetbrains

    - name: SSH
      ansible.builtin.import_tasks: ../../tasks/ssh.yml
      tags: ssh

    - name: PopOS
      ansible.builtin.import_tasks: ../../tasks/popos.yml
      tags: popos

    - name: VMWare
      ansible.builtin.import_tasks: ../../tasks/applications/vmware.yml
      when: "'vmware' in group_names"
      tags:
        - applications
        - vmware

    - name: Homebrew
      ansible.builtin.import_tasks: ../../tasks/brew.yml
      tags: brew

    - name: Tailscale
      ansible.builtin.import_role:
        name: artis3n.tailscale
      vars:
        tailscale_auth_key: '{{ TAILSCALE_AUTH_KEY }}'

  handlers:
    - name: Handlers
      ansible.builtin.import_tasks: ../../handlers/handlers.yml
