- name: Verify
  hosts: all
  gather_facts: true
  vars_files:
    - ../../files/vars.yml
  tasks:
    - name: Verify AWS Session Manager Plugin installation
      ansible.builtin.command: session-manager-plugin
      changed_when: false
      register: session_manager_plugin

    - name: Assertions
      ansible.builtin.assert:
        that:
          - session_manager_plugin.stdout == "\nThe Session Manager plugin was installed successfully. Use the AWS CLI to start a session."
