---

- name: Applications | Jetbrains Toolbox | Download
  ansible.builtin.get_url:
    url: "{{ jetbrains_toolbox_url }}"
    dest: "{{ install_dir }}/{{ jetbrains_toolbox }}"
    mode: 0644
  register: toolbox_app

- name: Applications | Jetbrains Toolbox | Un-package
  ansible.builtin.unarchive:
    src: "{{ toolbox_app.dest }}"
    remote_src: true
    dest: "{{ install_dir }}/"
  when: toolbox_app.changed  # noqa 503

- name: Applications | Jetbrains Toolbox | Locate installer
  ansible.builtin.shell: |
    set -o pipefail
    find . -maxdepth 1 -type d -name "jetbrains-toolbox-*" -print | head -n1
  args:
    executable: /bin/bash
    chdir: "{{ install_dir }}"
  changed_when: false
  register: toolbox_installer

- name: Applications | Jetbrains Toolbox | Install
  ansible.builtin.command: ./{{ toolbox_installer.stdout }}/jetbrains-toolbox
  args:
    chdir: "{{ install_dir }}"
    creates: '{{ home_dir }}/.local/share/applications/jetbrains-toolbox.desktop'
