---

- name: Applications | Keybase | Check for existence
  stat:
    path: /usr/bin/keybase
  register: keybase_binary

- name: Applications | Keybase | All actions
  block:
  - name: Applications | Keybase | Download
    get_url:
      url: "{{ keybase_url }}"
      dest: "{{ install_dir }}/{{ keybase_deb }}"
      mode: 0644

  - name: Applications | Keybase | Install
    become: yes
    apt:
      deb: "{{ install_dir }}/{{ keybase_deb }}"
    notify: Keybase Install

  when: not keybase_binary.stat.exists
