---

- name: Applications | VMWare | Check for program
  ansible.builtin.stat:
    path: /usr/bin/vmware
  register: vmware_app

- name: Applications | VMWare | Download
  ansible.builtin.get_url:
    url: "{{ vmware_url }}"
    dest: "{{ install_dir }}/vmware.bundle"
    mode: 0764
  when: not vmware_app.stat.exists
  register: vmware_installer

- name: Applications | VMWare | Install
  become: true
  ansible.builtin.command: bash {{ vmware_installer.dest }}
  args:
    creates: /usr/bin/vmware
  when: not vmware_app.stat.exists
