---

- name: Applications | VMWare | Download
  get_url:
    url: "{{ vmware_url }}"
    dest: "{{ install_dir }}/vmware.bundle"
    mode: 0764
  async: 1800
  poll: 30
  register: vmware_installer

- name: Applications | VMWare | Install
  become: yes
  command: bash {{ vmware_installer.dest }}
  args:
    creates: /usr/bin/vmware
