name: Ansible

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
          pipenv run ansible-galaxy install -r requirements.yml
          pipenv run ansible-galaxy collection install -r requirements.yml
          echo "${{ secrets.VAULT_PASS }}" > .vault_pass

      - name: Molecule
        run: pipenv run molecule test
