name: Ansible

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distros:
          - ghcr.io/artis3n/docker-ubuntu2010-ansible:latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          echo "${{ secrets.VAULT_PASS }}" > .vault_pass

      - name: Use Cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashfiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install packages
        run: |
          pipenv install --dev
          pipenv run ansible-galaxy install -r requirements.yml
          pipenv run ansible-galaxy collection install -r requirements.yml

      - name: Molecule
        run: pipenv run molecule test
        env:
          MOLECULE_DISTRO: "${{ matrix.distros }}"
