name: Ansible

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        molecule-os: [ubuntu1804]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Lint with Molecule
      run: pipenv run molecule lint

    - name: Test with Molecule
      run: |
        echo "ASecret" > .vault_pass
        cat files/secrets-example.yml > files/secrets.yml
        pipenv run ansible-vault encrypt --vault-id .vault_pass files/secrets.yml
        pipenv run molecule test
      env:
        MOLECULE_DISTRO: ${{ matrix.molecule-os }}
